print(" ")
adj1 = input("Enter an adjective: ")
pl1 = input("Enter a place: ")
noun1 = input("Enter a noun: ")
food1 = input("Enter a food: ")
emo1 = input("Enter an emotion: ")
adj2 = input("Enter an adjective: ")
noun2 = input("Enter a plural noun: ")

print(" ")
print("Title: My Dream Vacation")
print(" ")
print("I dream of going on a(n)", adj1, "vacation to", pl1, ".")
print("The thought of exploring", noun1, "and trying", food1, "makes me feel", emo1, ".") 
print("I can't wait to embark on this", adj2, "adventure and create lifelong", noun2, "along the way.")
print(" ")
print("End of the madlib.")